[workspace]
resolver = "2"
members = [
    "kodecks",
    "kodecks-bevy",
    "kodecks-bot",
    "kodecks-catalog",
    "kodecks-server",
]

[profile.dev]
debug = 0
strip = "debuginfo"
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.dev.package.kodecks-bot]
opt-level = 2

[profile.release]
opt-level = 3
panic = 'abort'
debug = 0
strip = "debuginfo"

[profile.distribution]
inherits = "release"
strip = true
lto = "thin"
codegen-units = 1
