name: Clippy

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.rs"
      - "**/*.toml"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.rs"
      - "**/*.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run clippy
        run: cargo clippy --verbose
