name: WASM

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.rs"
      - "**/*.toml"
      - "**/*.html"
      - "**/*.mjs"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.rs"
      - "**/*.toml"
      - "**/*.html"
      - "**/*.mjs"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --cfg=web_sys_unstable_apis

jobs:
  build_wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.3
      - name: Install trunk
        run: cargo binstall trunk --force -y
      - name: Build
        run: trunk build
