name: Web Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  deployments: write
  statuses: write

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ github.event_name }}
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.10.3
      - name: Install trunk
        run: cargo binstall trunk --force -y
      - name: Download assets
        run: ./scripts/download.sh
      - name: Build
        if: github.event_name == 'push'
        run: trunk build --cargo-profile web-distribution
      - name: Debug Build
        if: github.event_name == 'pull_request'
        run: trunk build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=kodecks
